### ISSUE TITLE
Unable to test insertAttendance.php from Postman

### ISSUE THREAD

**Issue by tejas2** [RajneeshSingh007/Attendance-App#6]
A message like Required parameters are missing is showing in the postman

@RajneeshSingh007

**Comment by tejas2** [comment]
![Screenshot (79)](https://user-images.githubusercontent.com/24987341/55874941-6ac2c880-5bb1-11e9-8840-59e40775a8b5.png)

**Comment by RajneeshSingh007** [comment]
Pass some formData and select mode to Post

**Comment by RajneeshSingh007** [comment]
Open file and check key of post
